// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAni1_EHKTehMfILwsRph9cqJs_u-n8Zlo',
    appId: '1:73736429630:web:6b7a9ce23bc6d3f65cb16f',
    messagingSenderId: '73736429630',
    projectId: 'shopping-online-de42d',
    authDomain: 'shopping-online-de42d.firebaseapp.com',
    storageBucket: 'shopping-online-de42d.appspot.com',
    measurementId: 'G-Y32HR83Y0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABvS_9glxbGYcOoI7b7UV9oWS2RII5ytQ',
    appId: '1:73736429630:android:6133333240d0b62e5cb16f',
    messagingSenderId: '73736429630',
    projectId: 'shopping-online-de42d',
    storageBucket: 'shopping-online-de42d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVvwWiTPnHbbl5ECAG_pVknuo6yv7qlcM',
    appId: '1:73736429630:ios:0e79b48be35316445cb16f',
    messagingSenderId: '73736429630',
    projectId: 'shopping-online-de42d',
    storageBucket: 'shopping-online-de42d.appspot.com',
    iosClientId: '73736429630-o4q79obr8ep845kmo7js1s9pc6kaflfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.productShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVvwWiTPnHbbl5ECAG_pVknuo6yv7qlcM',
    appId: '1:73736429630:ios:e141ea991bed10aa5cb16f',
    messagingSenderId: '73736429630',
    projectId: 'shopping-online-de42d',
    storageBucket: 'shopping-online-de42d.appspot.com',
    iosClientId: '73736429630-rv4lmba7ggsog7rbube38n9lbr4tq0g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.productShop.RunnerTests',
  );
}
